# Generated by Django 6.0.3 on 2026-03-09 00:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dinas', models.CharField(max_length=255, verbose_name='Nama Dinas')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dinas',
                'verbose_name_plural': 'Dinas',
                'ordering': ['nama_dinas'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_client', models.CharField(max_length=255, verbose_name='Nama Client')),
                ('no_hp', models.CharField(blank=True, default='', max_length=20, verbose_name='No. HP')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='finance.dinas', verbose_name='Dinas')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
                'ordering': ['nama_client'],
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('status_transfer', models.CharField(choices=[('Sudah Transfer', 'Sudah Transfer'), ('Belum', 'Belum')], default='Belum', max_length=20, verbose_name='Status Transfer')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_list', to='finance.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uang_masuk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Uang Masuk')),
                ('fee_5_persen', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='Fee 5%')),
                ('fee_bersih_80', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='Fee Bersih 80%')),
                ('fee_pemilik_20', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='Fee Pemilik 20%')),
                ('pajak', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Pajak')),
                ('bersih', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='Bersih')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.transaksi', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name': 'Detail Transaksi',
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
