# Generated by Django 5.2 on 2026-03-09 01:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksidetail',
            name='pajak',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, null=True, verbose_name='Pajak'),
        ),
    ]
