# Generated by Django 5.2 on 2026-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_client_user_dinas_user_transaksi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksidetail',
            name='fee_pemilik_sudah_ditransfer',
            field=models.BooleanField(default=False, verbose_name='Fee Pemilik Sudah Ditransfer?'),
        ),
    ]
