# Generated by Django 5.2 on 2026-03-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaksidetail_fee_pemilik_sudah_ditransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status_transfer',
            field=models.CharField(choices=[('Sudah Dibayar', 'Sudah Dibayar'), ('Belum Dibayar', 'Belum Dibayar')], default='Belum Dibayar', max_length=20, verbose_name='Status Pembayaran'),
        ),
    ]
