# Generated by Django 5.2 on 2026-03-09 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaksi_status_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='biaya_materai',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Biaya Materai'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='biaya_tte',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Biaya TTE'),
        ),
    ]
