# Generated by Django 6.0.3 on 2026-04-17 04:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaksi_biaya_materai_transaksi_biaya_tte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat_pesanan', models.CharField(max_length=255, verbose_name='Nomor Surat Pesanan')),
                ('tanggal_surat_pesanan', models.DateField(verbose_name='Tanggal Surat Pesanan')),
                ('nilai_pesanan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Nilai Pesanan (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_list', to='finance.client', verbose_name='Client (FK Client)')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
                'ordering': ['-tanggal_surat_pesanan'],
            },
        ),
    ]
