# Generated by Django 5.2 on 2026-05-05 02:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_pesanan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('no_nota', models.CharField(max_length=50, verbose_name='No. Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan_list', to='finance.dinas', verbose_name='Tuan / Toko (Dinas)')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
                'ordering': ['-tanggal', '-no_nota'],
            },
        ),
        migrations.CreateModel(
            name='PenjualanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='QTY')),
                ('nama_barang', models.CharField(max_length=255, verbose_name='Nama Barang')),
                ('satuan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Satuan (Harga)')),
                ('jumlah', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='Jumlah')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.penjualan', verbose_name='Penjualan')),
            ],
            options={
                'verbose_name': 'Detail Penjualan',
                'verbose_name_plural': 'Detail Penjualan',
            },
        ),
    ]
